### ISSUE TITLE
file is missing

### ISSUE THREAD

**Issue by yuvraj-pandey** [r4tylmz/yolo-dlib-face-recognition#2]
[Errno 2] No such file or directory: 'FaceRecognizer/files/encodings.pickle'

when i was running constants.py file

**Comment by r4tylmz** [comment]
You need to read carefully https://github.com/r4tylmz/yolo-dlib-face-recognition page. I wrote it down there clearly. Just follow the instructions and you need to use a backend for the project https://github.com/r4tylmz/staff-track-java
